//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MellatPayment2ProgrammingClass
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientConfirmRequestData", Namespace="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MellatPayment2ProgrammingClass.ClientConfirmWithAmountRequestData))]
    public partial class ClientConfirmRequestData : object
    {
        
        private string LoginAccountField;
        
        private long TokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LoginAccount
        {
            get
            {
                return this.LoginAccountField;
            }
            set
            {
                this.LoginAccountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Token
        {
            get
            {
                return this.TokenField;
            }
            set
            {
                this.TokenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientConfirmWithAmountRequestData", Namespace="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService")]
    public partial class ClientConfirmWithAmountRequestData : MellatPayment2ProgrammingClass.ClientConfirmRequestData
    {
        
        private long OrderIdField;
        
        private long AmountField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long OrderId
        {
            get
            {
                return this.OrderIdField;
            }
            set
            {
                this.OrderIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public long Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientConfirmResponseData", Namespace="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MellatPayment2ProgrammingClass.ClientConfirmResponseDataAddData))]
    public partial class ClientConfirmResponseData : object
    {
        
        private short StatusField;
        
        private string CardNumberMaskedField;
        
        private long RRNField;
        
        private long TokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CardNumberMasked
        {
            get
            {
                return this.CardNumberMaskedField;
            }
            set
            {
                this.CardNumberMaskedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public long RRN
        {
            get
            {
                return this.RRNField;
            }
            set
            {
                this.RRNField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public long Token
        {
            get
            {
                return this.TokenField;
            }
            set
            {
                this.TokenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientConfirmResponseDataAddData", Namespace="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService")]
    public partial class ClientConfirmResponseDataAddData : MellatPayment2ProgrammingClass.ClientConfirmResponseData
    {
        
        private string AddDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AddData
        {
            get
            {
                return this.AddDataField;
            }
            set
            {
                this.AddDataField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService", ConfigurationName="MellatPayment2ProgrammingClass.ConfirmServiceSoap")]
    public interface ConfirmServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService/ConfirmPayment", ReplyAction="*")]
        System.Threading.Tasks.Task<MellatPayment2ProgrammingClass.ConfirmPaymentResponse> ConfirmPaymentAsync(MellatPayment2ProgrammingClass.ConfirmPaymentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService/ConfirmPaymentWithA" +
            "ddData", ReplyAction="*")]
        System.Threading.Tasks.Task<MellatPayment2ProgrammingClass.ConfirmPaymentWithAddDataResponse> ConfirmPaymentWithAddDataAsync(MellatPayment2ProgrammingClass.ConfirmPaymentWithAddDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService/ConfirmPaymentWithA" +
            "mount", ReplyAction="*")]
        System.Threading.Tasks.Task<MellatPayment2ProgrammingClass.ConfirmPaymentWithAmountResponse> ConfirmPaymentWithAmountAsync(MellatPayment2ProgrammingClass.ConfirmPaymentWithAmountRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConfirmPaymentRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConfirmPayment", Namespace="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService", Order=0)]
        public MellatPayment2ProgrammingClass.ConfirmPaymentRequestBody Body;
        
        public ConfirmPaymentRequest()
        {
        }
        
        public ConfirmPaymentRequest(MellatPayment2ProgrammingClass.ConfirmPaymentRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService")]
    public partial class ConfirmPaymentRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MellatPayment2ProgrammingClass.ClientConfirmRequestData requestData;
        
        public ConfirmPaymentRequestBody()
        {
        }
        
        public ConfirmPaymentRequestBody(MellatPayment2ProgrammingClass.ClientConfirmRequestData requestData)
        {
            this.requestData = requestData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConfirmPaymentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConfirmPaymentResponse", Namespace="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService", Order=0)]
        public MellatPayment2ProgrammingClass.ConfirmPaymentResponseBody Body;
        
        public ConfirmPaymentResponse()
        {
        }
        
        public ConfirmPaymentResponse(MellatPayment2ProgrammingClass.ConfirmPaymentResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService")]
    public partial class ConfirmPaymentResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MellatPayment2ProgrammingClass.ClientConfirmResponseData ConfirmPaymentResult;
        
        public ConfirmPaymentResponseBody()
        {
        }
        
        public ConfirmPaymentResponseBody(MellatPayment2ProgrammingClass.ClientConfirmResponseData ConfirmPaymentResult)
        {
            this.ConfirmPaymentResult = ConfirmPaymentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConfirmPaymentWithAddDataRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConfirmPaymentWithAddData", Namespace="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService", Order=0)]
        public MellatPayment2ProgrammingClass.ConfirmPaymentWithAddDataRequestBody Body;
        
        public ConfirmPaymentWithAddDataRequest()
        {
        }
        
        public ConfirmPaymentWithAddDataRequest(MellatPayment2ProgrammingClass.ConfirmPaymentWithAddDataRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService")]
    public partial class ConfirmPaymentWithAddDataRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MellatPayment2ProgrammingClass.ClientConfirmRequestData requestData;
        
        public ConfirmPaymentWithAddDataRequestBody()
        {
        }
        
        public ConfirmPaymentWithAddDataRequestBody(MellatPayment2ProgrammingClass.ClientConfirmRequestData requestData)
        {
            this.requestData = requestData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConfirmPaymentWithAddDataResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConfirmPaymentWithAddDataResponse", Namespace="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService", Order=0)]
        public MellatPayment2ProgrammingClass.ConfirmPaymentWithAddDataResponseBody Body;
        
        public ConfirmPaymentWithAddDataResponse()
        {
        }
        
        public ConfirmPaymentWithAddDataResponse(MellatPayment2ProgrammingClass.ConfirmPaymentWithAddDataResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService")]
    public partial class ConfirmPaymentWithAddDataResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MellatPayment2ProgrammingClass.ClientConfirmResponseDataAddData ConfirmPaymentWithAddDataResult;
        
        public ConfirmPaymentWithAddDataResponseBody()
        {
        }
        
        public ConfirmPaymentWithAddDataResponseBody(MellatPayment2ProgrammingClass.ClientConfirmResponseDataAddData ConfirmPaymentWithAddDataResult)
        {
            this.ConfirmPaymentWithAddDataResult = ConfirmPaymentWithAddDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConfirmPaymentWithAmountRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConfirmPaymentWithAmount", Namespace="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService", Order=0)]
        public MellatPayment2ProgrammingClass.ConfirmPaymentWithAmountRequestBody Body;
        
        public ConfirmPaymentWithAmountRequest()
        {
        }
        
        public ConfirmPaymentWithAmountRequest(MellatPayment2ProgrammingClass.ConfirmPaymentWithAmountRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService")]
    public partial class ConfirmPaymentWithAmountRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MellatPayment2ProgrammingClass.ClientConfirmWithAmountRequestData requestData;
        
        public ConfirmPaymentWithAmountRequestBody()
        {
        }
        
        public ConfirmPaymentWithAmountRequestBody(MellatPayment2ProgrammingClass.ClientConfirmWithAmountRequestData requestData)
        {
            this.requestData = requestData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConfirmPaymentWithAmountResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConfirmPaymentWithAmountResponse", Namespace="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService", Order=0)]
        public MellatPayment2ProgrammingClass.ConfirmPaymentWithAmountResponseBody Body;
        
        public ConfirmPaymentWithAmountResponse()
        {
        }
        
        public ConfirmPaymentWithAmountResponse(MellatPayment2ProgrammingClass.ConfirmPaymentWithAmountResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService")]
    public partial class ConfirmPaymentWithAmountResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MellatPayment2ProgrammingClass.ClientConfirmResponseData ConfirmPaymentWithAmountResult;
        
        public ConfirmPaymentWithAmountResponseBody()
        {
        }
        
        public ConfirmPaymentWithAmountResponseBody(MellatPayment2ProgrammingClass.ClientConfirmResponseData ConfirmPaymentWithAmountResult)
        {
            this.ConfirmPaymentWithAmountResult = ConfirmPaymentWithAmountResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface ConfirmServiceSoapChannel : MellatPayment2ProgrammingClass.ConfirmServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class ConfirmServiceSoapClient : System.ServiceModel.ClientBase<MellatPayment2ProgrammingClass.ConfirmServiceSoap>, MellatPayment2ProgrammingClass.ConfirmServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ConfirmServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ConfirmServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), ConfirmServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ConfirmServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ConfirmServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ConfirmServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ConfirmServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ConfirmServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MellatPayment2ProgrammingClass.ConfirmPaymentResponse> MellatPayment2ProgrammingClass.ConfirmServiceSoap.ConfirmPaymentAsync(MellatPayment2ProgrammingClass.ConfirmPaymentRequest request)
        {
            return base.Channel.ConfirmPaymentAsync(request);
        }
        
        public System.Threading.Tasks.Task<MellatPayment2ProgrammingClass.ConfirmPaymentResponse> ConfirmPaymentAsync(MellatPayment2ProgrammingClass.ClientConfirmRequestData requestData)
        {
            MellatPayment2ProgrammingClass.ConfirmPaymentRequest inValue = new MellatPayment2ProgrammingClass.ConfirmPaymentRequest();
            inValue.Body = new MellatPayment2ProgrammingClass.ConfirmPaymentRequestBody();
            inValue.Body.requestData = requestData;
            return ((MellatPayment2ProgrammingClass.ConfirmServiceSoap)(this)).ConfirmPaymentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MellatPayment2ProgrammingClass.ConfirmPaymentWithAddDataResponse> MellatPayment2ProgrammingClass.ConfirmServiceSoap.ConfirmPaymentWithAddDataAsync(MellatPayment2ProgrammingClass.ConfirmPaymentWithAddDataRequest request)
        {
            return base.Channel.ConfirmPaymentWithAddDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<MellatPayment2ProgrammingClass.ConfirmPaymentWithAddDataResponse> ConfirmPaymentWithAddDataAsync(MellatPayment2ProgrammingClass.ClientConfirmRequestData requestData)
        {
            MellatPayment2ProgrammingClass.ConfirmPaymentWithAddDataRequest inValue = new MellatPayment2ProgrammingClass.ConfirmPaymentWithAddDataRequest();
            inValue.Body = new MellatPayment2ProgrammingClass.ConfirmPaymentWithAddDataRequestBody();
            inValue.Body.requestData = requestData;
            return ((MellatPayment2ProgrammingClass.ConfirmServiceSoap)(this)).ConfirmPaymentWithAddDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MellatPayment2ProgrammingClass.ConfirmPaymentWithAmountResponse> MellatPayment2ProgrammingClass.ConfirmServiceSoap.ConfirmPaymentWithAmountAsync(MellatPayment2ProgrammingClass.ConfirmPaymentWithAmountRequest request)
        {
            return base.Channel.ConfirmPaymentWithAmountAsync(request);
        }
        
        public System.Threading.Tasks.Task<MellatPayment2ProgrammingClass.ConfirmPaymentWithAmountResponse> ConfirmPaymentWithAmountAsync(MellatPayment2ProgrammingClass.ClientConfirmWithAmountRequestData requestData)
        {
            MellatPayment2ProgrammingClass.ConfirmPaymentWithAmountRequest inValue = new MellatPayment2ProgrammingClass.ConfirmPaymentWithAmountRequest();
            inValue.Body = new MellatPayment2ProgrammingClass.ConfirmPaymentWithAmountRequestBody();
            inValue.Body.requestData = requestData;
            return ((MellatPayment2ProgrammingClass.ConfirmServiceSoap)(this)).ConfirmPaymentWithAmountAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ConfirmServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ConfirmServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ConfirmServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://pec.shaparak.ir/NewIPGServices/Confirm/ConfirmService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ConfirmServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://pec.shaparak.ir/NewIPGServices/Confirm/ConfirmService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ConfirmServiceSoap,
            
            ConfirmServiceSoap12,
        }
    }
}
